# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('client_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('client_update', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('client_name', models.CharField(max_length=48, verbose_name='\u0418\u043c\u044f \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('client_family', models.CharField(max_length=48, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('client_otchestvo', models.CharField(max_length=48, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('client_birthday', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('client_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('client_passport_number', models.IntegerField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043f\u0430\u0441\u043f\u043e\u0440\u0442\u0430')),
                ('client_scoring_point', models.SmallIntegerField(choices=[(1, b'10%'), (2, b'20%'), (3, b'30%'), (4, b'40%'), (5, b'50%'), (6, b'60%'), (7, b'70%'), (8, b'80%'), (9, b'90%'), (10, b'100%')], default=0, verbose_name='\u0441\u043a\u043e\u0440\u0438\u043d\u0433\u043e\u0432\u044b\u0439 \u0431\u0430\u043b\u043b')),
            ],
            options={
                'db_table': 'client',
                'verbose_name': '\u0410\u043d\u043a\u0435\u0442\u0430 \u043a\u043b\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u0410\u043d\u043a\u0435\u0442\u044b \u043a\u043b\u0438\u0435\u043d\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_application_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('credit_application_send', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('credit_application_status', models.SmallIntegerField(choices=[(0, '\u041d\u043e\u0432\u044b\u0439'), (1, '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043d\u044b\u0439')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('credit_application_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_credit_application', to='hunter_bank.Client')),
            ],
            options={
                'db_table': 'credit_application',
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430 \u0432 \u043a\u0440\u0435\u0434\u0438\u0442\u043d\u0443\u044e \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044e',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u0432 \u043a\u0440\u0435\u0434\u0438\u0442\u043d\u0443\u044e \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044e',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('offer_update', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('offer_rotation_begin', models.DateTimeField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u043e\u0442\u0430\u0446\u0438\u0438')),
                ('offer_rotation_end', models.DateTimeField(verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0440\u043e\u0442\u0430\u0446\u0438\u0438')),
                ('offer_name', models.CharField(max_length=120, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
                ('offer_type', models.SmallIntegerField(choices=[(0, '\u043f\u043e\u0442\u0440\u0435\u0431'), (1, '\u0438\u043f\u043e\u0442\u0435\u043a\u0430'), (2, '\u0430\u0432\u0442\u043e\u043a\u0440\u0435\u0434\u0438\u0442'), (3, '\u041a\u041c\u0421\u0411')], default=0, verbose_name='\u0422\u0438\u043f \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
                ('offer_minimal_scoring_point', models.SmallIntegerField(choices=[(1, b'10%'), (2, b'20%'), (3, b'30%'), (4, b'40%'), (5, b'50%'), (6, b'60%'), (7, b'70%'), (8, b'80%'), (9, b'90%'), (10, b'100%')], default=0, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0441\u043a\u043e\u0440\u0438\u043d\u0433\u043e\u0432\u044b\u0439 \u0431\u0430\u043b\u043b')),
                ('offer_maximal_scoring_point', models.SmallIntegerField(choices=[(1, b'10%'), (2, b'20%'), (3, b'30%'), (4, b'40%'), (5, b'50%'), (6, b'60%'), (7, b'70%'), (8, b'80%'), (9, b'90%'), (10, b'100%')], default=0, verbose_name='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0441\u043a\u043e\u0440\u0438\u043d\u0433\u043e\u0432\u044b\u0439 \u0431\u0430\u043b\u043b')),
            ],
            options={
                'db_table': 'offer',
                'verbose_name': '\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=120, verbose_name='\u041f\u0430\u0440\u0442\u043d\u0435\u0440')),
                ('organization_status', models.SmallIntegerField(choices=[(0, '\u041e\u0442\u043b\u0438\u0447\u043d\u043e'), (1, '\u0425\u043e\u0440\u043e\u0448\u043e'), (2, '\u041d\u043e\u0440\u043c\u0430\u043b\u044c\u043d\u043e'), (3, '\u041f\u043b\u043e\u0445\u043e'), (4, '\u041e\u0447\u0435\u043d\u044c \u043f\u043b\u043e\u0445\u043e')], default=0, verbose_name='\u0422\u0438\u043f \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'organization',
                'verbose_name_plural': '\u041f\u0430\u0440\u043d\u0435\u0440',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_credit_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunter_bank.Organization', verbose_name='\u041a\u0440\u0435\u0434\u0438\u0442\u043d\u0430\u044f \u043e\u0440\u0433\u043e\u043d\u0438\u0437\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='credit_application_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_credit_application', to='hunter_bank.Offer'),
        ),
    ]
